name: 'Codesphere Deploy'
description: 'Deploys the repository in Codesphere'
branding:
  icon: 'circle'
  color: 'purple'
runs:
  using: 'node16'
  main: 'main.js'
inputs:
  email:
    description: 'email of the codesphere user'
    required: true
  password:
    description: 'Password of the codesphere user account'
    required: true
  team:
    description: 'Name of the codesphere team'
    required: true
  plan:
    description: |
      Plan of the created workspace. 

      Available options:
      - Micro
      - Boost
      - Pro
    required: false
    default: 'Boost'
  env:
    description: |
      Set environment variables in your workspace.
      
      Use dotenv like environment variables definition.
      See https://www.npmjs.com/package/dotenv for details.
    required: false
  apiUrl:
    description: 'codesphere url'
    required: false
    default: 'https://codesphere.com'
outputs: {}
